apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tomcat"
  namespace: "tomcat"
spec:
  selector:
    matchLabels:
      app: "tomcat"
  replicas: 4
  template:
    metadata:
      labels:
        app: "tomcat"
    spec:
      containers:
      - image: ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/tomcat_backbase:latest
        imagePullPolicy: Always
        name: "tomcat"
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
