apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: backbase-tomcat
        image: dockersamples/static-site
        env:
        - name: AUTHOR
          value: gfechio
        ports:
        - containerPort: 8080
